
project_id = "peace2hearts"

[functions.send-email]
verify_jwt = true

[functions.razorpay]
verify_jwt = true

[functions.admin-auth]
verify_jwt = false

[functions.update-admin-password]
verify_jwt = false
